services:
  neo4j:
    image: neo4j:5.26-community
    container_name: neo4j-db
    restart: unless-stopped
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      # Authentication
      NEO4J_AUTH: neo4j/password123
      
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    
    healthcheck:
      test: ["CMD-SHELL", "cypher-shell -u neo4j -p password123 'RETURN 1'"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
volumes:
  neo4j_data:
  neo4j_logs:


